[project]
name = "hackathon-etal2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradio>=5.44.1",
    "gradio-pdf>=0.0.22",
    "markdown>=3.8.2",
]
